---
title: ''
output: html_document
---

### Preregistration Template for modelling in Ecology and Conservation

The template was developed for preregistration of model-based research within the fields of ecology and conservation science. We use the term 'model-based research' to refer to any study that uses a statistical, computational, or mathematical model as the primary tool of inference to answer its research questions, whether that be for explanation or for prediction. The template may be used for theoretical or applied research, and items X,Y,Z can be omitted or included depending on whether the study aims to inform specific policy or management decisions. The template is agnostic to the statistical framework underpinning the study, and can be used for Bayesian or for frequentist modelling frameworks.  Similarly, the template may be used to preregister models that span the spectrum of mechanistic or process-based to phenomenological models, and may be used for many different types of models built under many modelling frameworks. 

The hallmark feature of this preregistration is that it captures the model development process. The preregistration template is therefore designed to be used within an Adaptive Preregistration Framework, which aims to account for the iterative and non-linear cycle of model development, whilst also mitigating questionable research practices by constraining researcher degrees of freedom. 

### How to use this preregistration template?

The preregistration template should be used for a single study, including studies that may use multiple models. 

The hallmark feature of this preregistration is that it captures the model development process. The preregistration template is therefore designed to be used within an Adaptive Preregistration Framework, which aims to account for the iterative and non-linear cycle of model development whilst also mitigating questionable research practices by constraining researcher degrees of freedom. 

Please see [INSERT LINK]() to familiarise yourself with the process of adaptive preregistration. Whereas regular preregistration inventories all analysis decisions that will be made throughout the course of a study, and contains deterministic plans for each decision before collecting or observing data, adaptive preregistrations instead contain plans that allow for flexible strategies that describe different analytical choices that may be made depending on the observed outcome of some preceding analytical decision, much like a decision tree. 

**TBD**


-----

\* Feedback and recommendations for an update of the checklist can be provided here: INSERT LINK TO GH ISSUES REPO. 
